### ISSUE TITLE
sha256 sums

### ISSUE THREAD

**Issue by romanstingler** [archlinuxhardened/selinux#10]
==> Validating source files with sha256sums...
    setools-3.3.8.tar.bz2 ... Passed
    4560a00c872d0a664c1098585e5c1a209adf698b.patch ... FAILED
    76e333503433be018e8aee8992d8f77aa14979a5.patch ... FAILED
    ebf8c55a26abd7d5e088f9299a4d5c0df329446b.patch ... FAILED
    a85750fa6ed6570e29a52520317ec0986612eab9.patch ... FAILED
    0aa68c97dfd909d84242f3aca96923676770bf33.patch ... FAILED
    eefba53065bd522f3e053605d0c3a1d52a4aefbb.patch ... FAILED
    02bb44767963b38c0cd8f07c4ad55c23c67ebe9b.patch ... FAILED
    92fa9a361aa962e21701cc601c175ab5c6798583.patch ... FAILED
    f31571fd633c5ab6c76f6da4af2f0a0a2dc98f4e.patch ... FAILED
    6f3dd212e9b5d466628bb5be4263416057728219.patch ... FAILED
    8001568ca3914432ffc3825acb278a1e6d8293d9.patch ... FAILED
    4668d85ef6b078de110caf3aa6cdf89a7d8aa89d.patch ... FAILED
    f1e5b208d507171968ca4d2eeefd7980f1004a3c.patch ... FAILED

**Comment by fishilico** [comment]
Indeed. Github seems to have changed the number of digits in "index" lines. For example here is the diff I have for the first patch:
```diff
--- old/4560a00c872d0a664c1098585e5c1a209adf698b.patch	2016-12-21 04:06:01.978096397 +0100
+++ new/4560a00c872d0a664c1098585e5c1a209adf698b.patch	2017-06-01 23:16:32.473649844 +0200
@@ -10,7 +10,7 @@
  2 files changed, 6 insertions(+), 2 deletions(-)
 
 diff --git a/ChangeLog b/ChangeLog
-index 1bce21d..4d883f3 100644
+index 1bce21d8..4d883f3a 100644
 --- a/ChangeLog
 +++ b/ChangeLog
 @@ -1,3 +1,6 @@
@@ -21,7 +21,7 @@
  
  	* SETools 3.3.8
 diff --git a/sediff/progress.c b/sediff/progress.c
-index efaa120..09730dc 100644
+index efaa1204..09730dcf 100644
 --- a/sediff/progress.c
 +++ b/sediff/progress.c
 @@ -99,7 +99,7 @@ void progress_hide(progress_t * progress)
```

I have updated the sha256sums array. Thanks for your report!
