### ISSUE TITLE
ALPM Hook Multithreading

### ISSUE THREAD

**Issue by 5265644D61736F6E** [archlinuxhardened/selinux#101]
At [selinux-alpm-hook:31](https://github.com/archlinuxhardened/selinux/blob/master/selinux-alpm-hook/selinux-alpm-hook#L31) and [selinux-alpm-hook:86](https://github.com/archlinuxhardened/selinux/blob/master/selinux-alpm-hook/selinux-alpm-hook#L86), restorecon runs on a single thread. Could it run multi-threaded (`-T0`) so it's more bearable to install and upgrade packages?

I think the generated directory relabeling should take on a structure similar to the package file relabeling so the former can take full advantage of all threads, even when moving to the next directory.

**Comment by fishilico** [comment]
Thanks for your suggestion. I agree with adding `-T0`. I did this in commit https://aur.archlinux.org/cgit/aur.git/commit/?h=selinux-alpm-hook&id=4163d5df5929abd136da797806a5e2554e9b7291 and bumped the version to 0.1-4.
