### ISSUE TITLE
Arch linux is now with util-linux 2.40

### ISSUE THREAD

**Issue by bda65hp** [archlinuxhardened/selinux#121]
Hi all,

Since some days, Arch Linux need util-linux 2.40. But util-linux-selinux is at 2.39.

If updated, arch installation with selinux do not work anymore.

**Comment by fishilico** [comment]
Thanks for your report. I am not able to currently test any update and will work on this next week. In the mean time, if someone tests and submits a package update through a Pull Request, I will probably be able to merge it (and release the update) on Monday, being more confident that it works properly.

**Comment by fishilico** [comment]
Hello,
I updated the package (https://github.com/archlinuxhardened/selinux/commit/3378558211f83c575119c0a6d955022d4deeda2d) and after fixing a CI issue related to git-cloning `systemd`'s repository (https://github.com/archlinuxhardened/selinux/commit/c506b181291f0a59a8f1b64ef1682df49d4c007d), it successfully built and the new packages are available on https://github.com/archlinuxhardened/selinux/releases/tag/ArchLinux-SELinux .

Therefore I am closing this issue now. If you encounter a problem with this update, please open a new GitHub issue.
