### ISSUE TITLE
not install errors

### ISSUE THREAD

**Issue by skarpinis** [archlinuxhardened/selinux#125]
==> Starting check()...
/usr/lib/python3.12/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'test'
==> ERROR: A failure occurred in check().
    Aborting...

**Comment by fishilico** [comment]
Hello,
Thanks for your report. The issue in `setools` should be fixed with setools 4.5.1-2 (in https://github.com/archlinuxhardened/selinux/commit/6485923ae864d698939be942125459f424a244ce).

If the issue still exists, please comment and I'll re-open this issue.
