### ISSUE TITLE
SElinux ia available in official Arch kernel

### ISSUE THREAD

**Issue by Maryse47** [archlinuxhardened/selinux#19]
Does it make sense to maintain linux-selinux anymore? It only takes to add `selinux=1 security=selinux` in cmdline in official kernels.

https://wiki.archlinux.org/index.php/SELinux#Current_status_in_Arch_Linux

**Comment by fishilico** [comment]
The last time SELinux was enabled in Arch Linux configuration, it barely survived a week, and it was last month (cf. https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=c75a915313f72924fa0a3ed45356f9e0ea488f3b and https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=62b80117614b44f4a17921b0d1cb9b9e6d08fa4e). The previous attempt survived 3 months (it has been introduced in 3.13 in https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=a1bf3bc4dde855b65095714189f5dccf562b0d9f and dropped in 3.14 with https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=be17a7f9fa44af6d1c48c08196f003fb365da822). As I am not aware of what has caused Arch Linux kernel maintainers to change their mind, I will wait for some months before dropping `linux-selinux` maintenance.

**Comment by Maryse47** [comment]
Right. I know all of this very well. Disabling it again will be ridiculous.

BTW: [AppArmor userspace tools](https://www.archlinux.org/packages/community-testing/x86_64/apparmor/) will be soon in official repos.
