### ISSUE TITLE
python2-audit removed

### ISSUE THREAD

**Issue by alexa-v2** [archlinuxhardened/selinux#24]
The package python2-audit has been removed from the core repo (see https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/audit&id=3a2d7bcf6e1ce0894b3c5601d2569df9a47383b6)

The build_and_install_all.sh still uses this package, which obviously throws an error

**Comment by unsaved** [comment]
If anybody is stuck at this step, this workaround seems to work:  From a clean clone (or do a clean if you can figure that out), edit PKGBUILD and change the occurrence of "python2-audit" to "python-audit".

**Comment by fishilico** [comment]
Thanks for the report. I removed `python2-audit` from the dependency array of `selinux-python2`. As more and more Python2 packages are removed, I plan to remove this package when the next release of the SELinux python bindings will be published.
