### ISSUE TITLE
404 Error for the repository

### ISSUE THREAD

**Issue by pwnage-pineapple** [archlinuxhardened/selinux#3]
I click on the link for the repository and I am presented with a 404 error

**Comment by fishilico** [comment]
Hello, which link are you talking about? Where did you find it?

**Comment by pwnage-pineapple** [comment]
I'm talking about the binary repository in the README

**Comment by Siosm** [comment]
I took it down because it was completely outdated as I couldn't keep up with updating packages on my free time.
