### ISSUE TITLE
Can't finish compiling latest version of systemd-selinux on Arch Linux

### ISSUE THREAD

**Issue by zhanghua000** [archlinuxhardened/selinux#31]
I am upgrading my Arch Linux but when compiling `systemd-selinux` and `systemd-lib-selinux`, it will fail to build these two packages. I put output below, please help me to solve this problem. Thank you in advance.
Terminal output when it starts building:
https://paste.ubuntu.com/p/pNJdgmGRwg/

**Comment by fishilico** [comment]
Thanks for your report. It is a bug that was triggered by the upgrade of `libmicrohttpd` to version 0.9.71-1 (it was updated in `core` repository on 2020-06-30, according to https://git.archlinux.org/svntogit/packages.git/log/?h=packages/libmicrohttpd).

The main systemd repository already has a fix for this bug: https://github.com/systemd/systemd/commit/d17eabb1052e7c8c432331a7a782845e36164f01. I will try backporting this patch and if it is enough, I will update package `systemd-selinux`.

In the mean time, downgrading `libmicrohttpd` to version 0.9.70-3 should fix your issue too.
