### ISSUE TITLE
setools update

### ISSUE THREAD

**Issue by xavloose** [archlinuxhardened/selinux#5]
python2-enum34 is listed as an optional dependency but setools failed to build without it. Did I do something wrong or is it a make dependency too?

**Comment by fishilico** [comment]
I added python2-enum34 to checkdepends (https://github.com/archlinuxhardened/selinux/commit/b9f1f39e070644d05859e6c5676bb122a9ef137d) and not to makedepends, because ``makepkg --no-check`` works fine on a system without python2-enum34. Thanks for the bug report!
