### ISSUE TITLE
iproute2-selinux-doc and iproute2 conflict

### ISSUE THREAD

**Issue by sorin-mihai** [archlinuxhardened/selinux#7]
Hello,

I only went briefly over the documentation and then used the build_and_install_all.sh script.
So far, all seems fine, except the following error.

[...]
looking for conflicting packages...
:: iproute2-selinux and iproute2 are in conflict (iproute). Remove iproute2? [y/N] y

Package (3)           Old Version  New Version  Net Change

iproute2              4.10.0-2                   -1.70 MiB
iproute2-selinux                   4.10.0-2       1.78 MiB
iproute2-selinux-doc               4.10.0-2       1.27 MiB

Total Installed Size:  3.04 MiB
Net Upgrade Size:      1.34 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                                                                                      [######################################################################] 100%
(2/2) checking package integrity                                                                                    [######################################################################] 100%
(2/2) loading package files                                                                                         [######################################################################] 100%
(2/2) checking for file conflicts                                                                                   [######################################################################] 100%
error: failed to commit transaction (conflicting files)
iproute2-selinux-doc: /usr/share/doc/iproute2/api-ip6-flowlabels.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/arpd.html exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/arpd.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/README.cbq exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/README.iproute2+tc exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/SYN-DoS.rate.limit exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/cbq.init-v0.7.3 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/cbqinit.eth1 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/dhcp-client-script exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge1 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge2 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge31-ca-u32 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge31-cb-chains exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge32-ca-u32 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge32-cb-chains exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/Edge32-cb-u32 exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/README exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/afcbq exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/ef-prio exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/efcbq exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/diffserv/regression-testing exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/examples/gaiconf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/ip-cref.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/ip-tunnels.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/nstat.html exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/nstat.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/rtstat.html exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/rtstat.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/ss.html exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/ss.pdf exists in filesystem
iproute2-selinux-doc: /usr/share/doc/iproute2/tc-filters.pdf exists in filesystem
Errors occurred, no packages were upgraded.
expect returned an error (1) when running: pacman -U ./iproute2-selinux/iproute2-selinux-4.10.0-2-x86_64.pkg.tar.xz ./iproute2-selinux/iproute2-selinux-doc-4.10.0-2-x86_64.pkg.tar.xz

I don't think this is the recommended way to deal with package conflicts in Arch, but to work around it for now, I just moved the /usr/share/doc/iproute2 folder out of the way and restarted the script.

**Comment by fishilico** [comment]
Thanks for your report! It was a bug in the package, which was missing "conflicts = iproute2-doc".
