### ISSUE TITLE
firewalld fails to load after rebuild

### ISSUE THREAD

**Issue by Caligino** [archlinuxhardened/selinux#75]
Attempting to start firewalld results in this error.
` firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-01-13 10:21:01 EST; 30s ago
       Docs: man:firewalld(1)
    Process: 26214 ExecStart=/usr/bin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=1/FAILURE)
   Main PID: 26214 (code=exited, `status=1/FAILURE)

Jan 13 10:21:01 variation.nine systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 13 10:21:01 variation.nine systemd[1]: firewalld.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 10:21:01 variation.nine systemd[1]: firewalld.service: Failed with result 'exit-code'.
Jan 13 10:21:01 variation.nine systemd[1]: Failed to start firewalld - dynamic firewall daemon.`

Arch doesnt activate the rebuilt version of dbus. i suspect it's not pointing to the correct system path but i'm not sure.

`dbus-daemon[516]:` [system] Activation via systemd failed for unit 'dbus-org.freedesktop.resolve1.service' requested by ':1.2325' (uid=0 pid=26440 comm="resolvconf -a enp5s0.ra " label="system_u:system_r:kernel_t")
service name='org.freedesktop.resolve1' unit=dbus-org.freedesktop.resolve1.service not found.`

**Comment by tqre** [comment]
This doesn't sound like a problem related to this repository, maybe Arch Forums would be better place to ask this?
https://bbs.archlinux.org/

**Comment by fishilico** [comment]
closing, at it does not seem to be related to SELinux.
