### ISSUE TITLE
[enforcing][login][root/other_users]

### ISSUE THREAD

**Issue by javlock** [archlinuxhardened/selinux#98]
why is it not possible for root or other users to log into the tty in denied mode?

**Comment by fishilico** [comment]
Hello,
There could be an issue in the way the SELinux policy on your system is configured. In order to better debug this issue, did you find messages in `/var/log/audit/audit.log` related to the denials?

**Comment by jMeTeora** [comment]
(I am writing from another account because the hard drive died, there was no backup)

Good afternoon @fishilico, I checked with audit2allow -ar and added to my rules.

i use systemd-boot

in kernel option: lsm=landlock,lockdown,yama,selinux,bpf

```
checkmodule -M -m -o jmeteora_fix.mod jmeteora_fix.te
semodule_package -o jmeteora_fix.pp -m jmeteora_fix.mod
semodule -i jmeteora_fix.pp
```

**Comment by jMeTeora** [comment]
(now with permissive mod)
with enforcing no logon (
```
cat /etc/selinux/config|grep -Ev "^#"
SELINUX=permissive
SELINUXTYPE=refpolicy-arch
```



etc/passwd

```
root:x:0:0::/root:/bin/bash
user:x:1000:1000::/home/user:/bin/bash
```

specially made a git repository in /etc to track changes (to roll back if I break, DAC: ug:root u=wr,go-wrx )
here are the differences:
```
git diff security/access.conf
++:root:LOCAL
++:root:ALL
```




```
cat security/access.conf|grep -vE "^#"
+:root:LOCAL
+:root:ALL
```

**Comment by jMeTeora** [comment]
cat /etc/securetty
```
console
tty1
tty2
tty3
tty4
tty5
tty6
ttyS0
hvc0
```

cat /etc/pacman.conf
```
[selinux]
Server = https://github.com/archlinuxhardened/selinux/releases/download/ArchLinux-SELinux
SigLevel = Never

```

**Comment by jMeTeora** [comment]
cat /etc/pam.d/system-login
```
#%PAM-1.0

auth       required   pam_shells.so
auth       requisite  pam_nologin.so
auth       include    system-auth

account    required   pam_access.so
account    required   pam_nologin.so
account    include    system-auth

password   include    system-auth

# pam_selinux.so close should be the first session rule
session    required   pam_selinux.so close
session    optional   pam_loginuid.so
session    optional   pam_keyinit.so       force revoke
session    include    system-auth
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required   pam_selinux.so open
session    optional   pam_motd.so
session    optional   pam_mail.so          dir=/var/spool/mail standard quiet
-session   optional   pam_systemd.so
session    required   pam_env.so           user_readenv=1
```

**Comment by jMeTeora** [comment]
where, besides journalctl and /var/log/audit/*, can I see logs about authorization, (also how to enable pam debugging) ?

**Comment by jMeTeora** [comment]
semanage login -l
```
__default__               user_u                   
root                      root
```

semanage user -l
```
root            staff_r sysadm_r
staff_u         staff_r sysadm_r
sysadm_u        sysadm_r
system_u        system_r
unconfined_u    unconfined_r
user_u          user_r
```

**Comment by jMeTeora** [comment]
using sshd i can login
![Скриншот_Выберите область_20220129073750](https://user-images.githubusercontent.com/97601008/151652345-f24f1231-2d65-4558-b5ac-c6ea05a9a36c.png)

**Comment by jMeTeora** [comment]
the problem arose due to selinux,
solved it by turning on showing non-logged exceptions using ```semodule --disable_dontaudit --build```

after reading, please add this hint to the repository readme and close the issue
